image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - check

mypy:
  stage: check
  rules:
    - changes:
      - metadatacleaner/**/*.py
  script:
    - pip install mypy
    - mypy --ignore-missing-imports ./metadatacleaner

pydocstyle:
  stage: check
  rules:
    - changes:
      - metadatacleaner/**/*.py
  script:
    - pip install pydocstyle
    - pydocstyle ./metadatacleaner
