# SPDX-FileCopyrightText: 2020, 2021 Romain Vigier <contact AT romainvigier.fr>
# SPDX-License-Identifier: GPL-3.0-or-later

variables:
  APP_ID: fr.romainvigier.MetadataCleaner
  MANIFEST: build-aux/fr.romainvigier.MetadataCleaner.yaml

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - check
  - build
  - bundle
  - deploy

.python:
  image: python:latest
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    key: python
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate

mypy:
  extends: .python
  stage: check
  rules:
    - changes:
      - metadatacleaner/**/*.py
  script:
    - pip install mypy
    - mypy --ignore-missing-imports ./metadatacleaner

pydocstyle:
  extends: .python
  stage: check
  rules:
    - changes:
      - metadatacleaner/**/*.py
  script:
    - pip install pydocstyle
    - pydocstyle ./metadatacleaner

pycodestyle:
  extends: .python
  stage: check
  rules:
    - changes:
      - metadatacleaner/**/*.py
  script:
    - pip install pycodestyle
    - pycodestyle ./metadatacleaner

reuse:
  extends: .python
  stage: check
  script:
    - pip install reuse
    - reuse lint

flatpak-repo:
  stage: build
  needs:
    - job: mypy
      optional: true
    - job: pydocstyle
      optional: true
    - job: pycodestyle
      optional: true
    - reuse
  image: registry.gitlab.com/rmnvgr/metadata-cleaner/flatpak-builder:latest
  cache:
    - key: flatpak-repo-$CI_COMMIT_REF_SLUG
      paths:
        - .flatpak-builder
  script:
    - if [[ -v CI_COMMIT_TAG ]]; then build-aux/prepare_release.py; fi
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak-builder --install-deps-from=flathub --repo=repo --default-branch=$CI_COMMIT_REF_NAME --ccache --disable-rofiles-fuse builddir $MANIFEST
  artifacts:
    name: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-flatpak-repo
    paths:
      - repo
    expire_in: 1 day

app:
  stage: bundle
  needs:
    - job: flatpak-repo
      artifacts: true
  image: registry.gitlab.com/rmnvgr/metadata-cleaner/flatpak-builder:latest
  script:
    - flatpak build-bundle ./repo $APP_ID.flatpak $APP_ID $CI_COMMIT_REF_NAME
  artifacts:
    name: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-flatpak
    expose_as: Flatpak bundle
    paths:
      - fr.romainvigier.MetadataCleaner.flatpak
    expire_in: 1 day

debug:
  stage: bundle
  needs:
    - job: flatpak-repo
      artifacts: true
  image: registry.gitlab.com/rmnvgr/metadata-cleaner/flatpak-builder:latest
  script:
    - flatpak build-bundle --runtime ./repo $APP_ID.Debug.flatpak $APP_ID.Debug $CI_COMMIT_REF_NAME
  artifacts:
    name: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-flatpak-debug
    expose_as: Flatpak debug symbols
    paths:
      - fr.romainvigier.MetadataCleaner.Debug.flatpak
    expire_in: 1 day

package:
  stage: deploy
  needs:
    - job: app
      artifacts: true
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $APP_ID.flatpak "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/metadata-cleaner/$CI_COMMIT_TAG/$APP_ID.flatpak"'

pages:
  stage: deploy
  needs: []
  image: registry.gitlab.com/rmnvgr/metadata-cleaner/flatpak-builder:latest
  script:
    - cp -r website public
    - cp -r data/screenshots public/screenshots
    - find public -type f -regex '.*\.\(|html\|css\|svg\|png\|woff\|woff2\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(|html\|css\|svg\|png\|woff\|woff2\)$' -exec brotli -f -k {} \;
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - "website/**/*"
  artifacts:
    paths:
      - public
    expire_in: 1 day
